package com.arduinocompiler.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF00838F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB2EBF2)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF4A5F63)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE2E7)
val md_theme_light_onSecondaryContainer = Color(0xFF061D20)
val md_theme_light_tertiary = Color(0xFF795548)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD7CCC8)
val md_theme_light_onTertiaryContainer = Color(0xFF2C150E)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFAFDFD)
val md_theme_light_onBackground = Color(0xFF191C1D)
val md_theme_light_surface = Color(0xFFFAFDFD)
val md_theme_light_onSurface = Color(0xFF191C1D)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E7)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797B)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF4DD0E1)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF4DD0E1)
val md_theme_dark_onPrimary = Color(0xFF003640)
val md_theme_dark_primaryContainer = Color(0xFF004D5C)
val md_theme_dark_onPrimaryContainer = Color(0xFFB2EBF2)
val md_theme_dark_secondary = Color(0xFFB0CBCF)
val md_theme_dark_onSecondary = Color(0xFF1B3235)
val md_theme_dark_secondaryContainer = Color(0xFF31484C)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE2E7)
val md_theme_dark_tertiary = Color(0xFFBCADB0)
val md_theme_dark_onTertiary = Color(0xFF422A23)
val md_theme_dark_tertiaryContainer = Color(0xFF5A403A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD7CCC8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1D)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF191C1D)
val md_theme_dark_onSurface = Color(0xFFE1E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9CB)
val md_theme_dark_outline = Color(0xFF899395)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1D)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inversePrimary = Color(0xFF00838F)

// Code Editor Colors
val EditorBackground = Color(0xFF1E1E1E)
val EditorKeyword = Color(0xFFC678DD)
val EditorString = Color(0xFF98C379)
val EditorComment = Color(0xFF5C6370)
val EditorFunction = Color(0xFF61AFEF)
val EditorNumber = Color(0xFFD19A66)
